### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by victory3398** [SharifAmit/RVGAN#18]
![1667311930327](https://user-images.githubusercontent.com/58261912/199253845-445f0d55-7a74-417e-8185-7038633ff9b6.png)
I meet i problem. I don't understand you how to solve the data number is small,and how to get the number 4320 for STARE、15120 for CHASE-DB1、4200 for DRIVE .can you explain it? or send me your preprocess datasets. Thanks!!!

**Comment by SharifAmit** [comment]
Hi,

Please check the following two codes : [strided_crop_DRIVE.py](https://github.com/SharifAmit/RVGAN/blob/master/strided_crop_DRIVE.py) and [convert_npz_DRIVE.py](https://github.com/SharifAmit/RVGAN/blob/master/convert_npz_DRIVE.py)

We have similar codes for CHASE and STARE as well in this repository. 

Basically, we use a strided crop operation with resolution 128x128 to get the 4310, 15120 and 4200 images for STARE, CHASE and DRIVE dataset.

**Comment by victory3398** [comment]
![1667354925216](https://user-images.githubusercontent.com/58261912/199378670-22f407f1-0b8b-4be9-b9a0-234c883c6cbf.png)

Tranks!  But I have the second questioin,the test dataset images is original shape and reshape it to 128x128,not crop it,only with stride = 3?

**Comment by SharifAmit** [comment]
For inference, please check the following [code](https://github.com/SharifAmit/RVGAN/blob/master/infer.py).

For testing we do not resize the image to 128x128. Rather, we take overlapping strided crop to create test crops, however the stride size is small s=3 to get finer segmentation results. The reason is after you have all the prediction test crops, you stitch and combine to get the original sized test image.

**Comment by victory3398** [comment]
Perfectly! I will try to do this work ,Thanks!!!

**Comment by SharifAmit** [comment]
Thanks, closing the issue.

Please reopen the issue if you have more questions !
